CI scripts review

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,4 +22,16 @@ jobs:
     - name: Build
       run: dotnet build -c Release
     - name: Test
-      run: dotnet test -c Release --no-build --verbosity normal
+      run: dotnet test -c Release --no-build --verbosity normal --logger="trx;logfilename=TestResults.trx"
+    - name: Reporting
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
+      with:
+        name: 'Test results report'
+        reporter: 'dotnet-trx'
+        path: '**/TestResults/TestResults.trx'
+        only-summary: 'true'
+        max-annotations: '10'
+        fail-on-error: 'true'
+        list-suites: 'failed'
+        list-tests: 'failed'
